### ISSUE TITLE
can you show  the microPyhton code about ESP32 ,pls?

### ISSUE THREAD

**Issue by bensontung** [sparkleo-io/flutter_ota#7]
how the devices receive the file? can you show the code?

**Comment by joshuadutton** [comment]
> how the devices receive the file? can you show the code?

@bensontung this (almost) works with this project: https://github.com/michael-angerer/esp32_ble_ota. That one is built in C using esp-idf and the nimble bluetooth stack. I recently got it working with a few adjustments to the Flutter code (the `chunkSize` is not calculated correctly, or at least not in the correct place, in the Flutter code). I'm planning on pushing a PR with my changes along with a working example, if I have some time. Let me know if that would help you.

If you need a micoPython example, I can't help you there, but the C source code and the related blog posts are really helpful for guidance (blog posts: https://michaelangerer.dev/esp32/ble/ota/2021/06/01/esp32-ota-part-1.html)

**Comment by afzl-wtu** [comment]
> > how the devices receive the file? can you show the code?
> 
> @bensontung this (almost) works with this project: https://github.com/michael-angerer/esp32_ble_ota. That one is built in C using esp-idf and the nimble bluetooth stack. I recently got it working with a few adjustments to the Flutter code (the `chunkSize` is not calculated correctly, or at least not in the correct place, in the Flutter code). I'm planning on pushing a PR with my changes along with a working example, if I have some time. Let me know if that would help you.
> 
> If you need a micoPython example, I can't help you there, but the C source code and the related blog posts are really helpful for guidance (blog posts: https://michaelangerer.dev/esp32/ble/ota/2021/06/01/esp32-ota-part-1.html)

yes please create a PR

**Comment by MinhalWaheed2001** [comment]
> how the devices receive the file? can you show the code?

@bensontung This works with this project : https://github.com/michael-angerer/esp32_ble_ota contains the firmware that recieves the file using specific protocols explained in README file for ESP-IDF firmware , also the recent merge has resolved the the chunkSize issue , now you can implement the ota update. Additionally, there's a requirement for this ESP-IDF-based firmware, you need to include updateType == 1 in your response. Is there anything specific you need assistance with regarding this update?
